
# Analysis {#analysis}

## Overview {#analysis-overview}

```{r eval=FALSE, exercise=TRUE}
install.packages("ggplot2")
install.packages("corrr")
install.packages("dbplot")
install.packages("rmarkdown")
```

```{r}
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local", version = "2.3")
```

## Import

```{r analysis-copy-to}
cars <- copy_to(sc, mtcars)
```

## Wrangle

```{r analysis-group-summarize}
cars %>%
  mutate(transmission = ifelse(am == 0, "automatic", "manual")) %>%
  group_by(transmission) %>%
  summarise_all(mean)
```

### Built-in Functions

```{r analysis-percentile}
summarise(cars, mpg_percentile = percentile(mpg, 0.25))
```

```{r analysis-percentile-query}
summarise(cars, mpg_percentile = percentile(mpg, 0.25)) %>%
  show_query()
```

```{r analysis-percentile-rename}
summarise(cars, mpg_percentile = percentile(mpg, array(0.25, 0.5, 0.75)))
```

```{r analysis-percentile-mutate}
summarise(cars, mpg_percentile = percentile(mpg, array(0.25, 0.5, 0.75))) %>%
  mutate(mpg_percentile = explode(mpg_percentile))
```

### Correlations

```{r analysis-corrr-cars}
ml_corr(cars)
```

```{r analysis-corrr-pairwise}
library(corrr)
correlate(cars, use = "pairwise.complete.obs", method = "pearson") 
```

```{r analysis-corrr-show}
correlate(cars, use = "pairwise.complete.obs", method = "pearson") %>%
  shave() %>%
  rplot()
```

## Visualize
